#!/bin/sh
# Copyright 2011 Brent Longborough
# Please read gitinfo.pdf for licencing and other details
# -----------------------------------------------------
# Post-{commit,checkout,merge} hook for the gitinfo package
#
prefixes="2022-2023/Stats 2022-2023/IntroPresentation 2021-2022/IntroPresentation 2020-2021/IntroPresentation 2021-2022/Stats 2020-2021/Stats 2019-2020/IntroPresentation 2019-2020/Stats  2015-2016/IntroPresentation 2015-2016/Stats 2016-2017/IntroPresentation 2016-2017/Stats 2017-2018/IntroPresentation 2017-2018/Stats 2018-2019/Stats 2018-2019/IntroPresentation"    # Example for multiple gitHeadInfo.tex files
# prefixes="."              # Default --- in the working copy root
for pref in $prefixes
	do
	git log -1 --date=short \
	--pretty=format:"\usepackage[%
		shash={%h},
		lhash={%H},
		authname={%an},
		authemail={%ae},
		authsdate={%ad},
		authidate={%ai},
		authudate={%at},
		commname={%an},
		commemail={%ae},
		commsdate={%ad},
		commidate={%ai},
		commudate={%at},
		refnames={%d}
	]{gitsetinfo}" HEAD > $pref/gitHeadInfo.gin
	done
